### PR TITLE
integrating the new design

### PR DESCRIPTION
**Pull request by rajraj**

### CODE REVIEW

**Comment by rajraj** [comment]
@andyunleashed many thanks for this.

One little change if possible. Would you be able to remove the green tint from the circles? Only from the outer circles. Is that done using CSS?

**Comment by andyunleashed** [comment]
Hi Raj,

My last request from Nikki was for the green gradient on the images - do they want to go back to just regular images with no shine?

Kind regards,

Andy

**Comment by rajraj** [comment]
If it's not too much trouble can I have one without the green gradient as well, please. 

I think the comment last time was the green stands out too much.

**Comment by andyunleashed** [comment]
Sure thing - I've added alternative.html that removes the green from the outside circles.

**Comment by rajraj** [comment]
Hi Andy,

Thanks for your help. Much appreciated.

As discussed would you be able to change the colour of the top part of outer circles to #feb900.
Also ask your graphics designer if the images can be made to look like a sphere without using any colour gradients.

**Comment by rajraj** [comment]
You can use a lighter version of the yellow as well if that looks better.

**Comment by andyunleashed** [comment]
Great stuff - Chris is going to have a look and see what he can do on the graphics.

**Pull request merged**
